### ISSUE TITLE
理解JS闭包|周末技术研讨第一期

### ISSUE THREAD

**Issue by youngjuning** [youngjuning/youngjuning#13]
### 什么是闭包

> 当一个函数能够保存所在的词法作用域时，就产生了闭包。并且不管在何时何地执行该函数都要可以访问到保存的词法作用域。

### 闭包的副作用

- 由于闭包会携带包含它的函数的作用域，因此会比其他函数占用更多的内存。
- 在IE9之前的浏览器中，如果闭包的作用域链中保存着HTML元素，那么就意味着该元素将无法被销毁。

### 循环中使用闭包解决 `var` 定义函数的问题

```js
for(var i = 1; i <=5: i++) {
  setTimeout(function timer() {
    console.log(i)
  }, i * 1000)
}
```

首先因为 `setTimeout` 是个异步函数，所以会把循环全部执行完毕，这时候 `i` 就是 6 了，所以会输出 5 个 6。

#### 使用闭包解决

```js
for(var i = 1; i <= 5; i++) {
  ;(function(j) {
    setTimeout(function timer() {
      console.log(j)
    }, j * 1000)
  })(i)
}
```

在上述代码中，我们首先使用了立即执行函数将 `i` 传入函数内部，这个时候值就被固定在了参数 `j` 上面不会改变，当下次执行 `timer` 这个闭包的时候，就可以使用外部函数的变量 `j`，从而达到目的。

#### 使用 setTimeout 的第三个参数

```js
for (var i = 1; i <= 5; i++) {
  setTimeout(
    function timer(j) {
      console.log(j)
    },
    i * 1000,
    i
  )
}
```

第三个参数会被当成 `timer` 函数的参数传入。

#### 使用let定义i

```js
for (let i = 1; i <= 5; i++) {
  setTimeout(function timer() {
    console.log(i)
  }, i * 1000)
}
```

**Comment by youngjuning** [comment]
- 你不知道的JavaScript上卷第一章中从原理上讲解了闭包，强烈建议读一读：![](https://user-images.githubusercontent.com/13204332/90327551-33470600-dfc7-11ea-8676-3fc3fef5f3e2.png)

**Comment by youngjuning** [comment]
## 涉及知识点

- 作用域与作用域链
- 匿名函数
- 自执行函数

**Comment by youngjuning** [comment]
## 是闭包吗？

```js
{
  let name = "closure"
  function sayHi() {
    return name
  }
}
sayHi()
```

**Comment by EwanBerg** [comment]
A closure is the combination of a function and the lexical environment within which that function was declared. -- MDN
闭包是函数和声明该函数的词法作用域的集合。
** 词法作用域 (lexical environment)

- 函数在执行的过程中，先从自己内部找变量
-如果找不到，再从**创建当前函数所在的作用域（词法作用域）**去找, 以此往上
-注意找的是变量的当前的状态
**函数连同它作用域链上的要找的这个变量，共同构成闭包**

**Comment by youngjuning** [comment]
> **函数A**里面包含了**函数B**，而**函数B**里面使用了**函数A**的变量，那么**函数B**被称为闭包函数。在JS中，闭包的意义是能让你从内部函数访问外部函数作用域。|《前端面试之道》

> 闭包是指有权访问另一个函数作用域中的变量的函数。创建闭包的常见方式，就是在一个函数内部创建另一个函数。|《JavaScript高级程序设计》

> 当函数可以记住并访问所在的词法作用域时，就产生了闭包，即使函数是在当前词法作用域之外执行的。|《你不知道的JavaScript 上卷》

> 在计算机科学中，闭包（Closure），又称词法闭包（Lexical Closure）或函数闭包（Function Closure），是在支持头等函数的编程语言中实现词法绑定的一种技术。闭包实际上是一个结构体，它存储了一个函数和一个关联环境。环境里是若干对符号和值的对应关系，它既要包括约束变量（该函数内部的变量），也要包括自由变量（在函数外部定义但在函数内被引用）。闭包跟函数最大的不同在于，当捕捉闭包的时候，它的自由变量会在捕捉时被确定，这样即便脱离了捕捉时的上下文，它也能照常运行。 |《维基百科》

**Comment by bifjhh** [comment]
> ## 是闭包吗？
> ### 是
> ```js
> { 
>   let  name  =  “ closure” 
>   函数 sayHi （） { 
>     返回 名称
>   } 
> } 
> sayHi （）
> ```
> 
> ### 不是

用 {} 相当于一个制造了作用域?
let定义 变量 不会有提升至全局, 但是function会提升到全局, 函数内部记录了当前作用域的`name`, 这样的方式也是一个闭包?

**Comment by youngjuning** [comment]
> > ## 是闭包吗？
> > ### 是
> > ```js
> > { 
> >   let  name  =  “ closure” 
> >   函数 sayHi （） { 
> >     返回 名称
> >   } 
> > } 
> > sayHi （）
> > ```
> > 
> > 
> > ### 不是
> 
> 用 {} 相当于一个制造了作用域?
> let定义 变量 不会有提升至全局, 但是function会提升到全局, 函数内部记录了当前作用域的`name`, 这样的方式也是一个闭包?

你这个话放大函数闭包也是说的通的，那么函数闭包就不是闭包了？

这个问题的核心在于函数闭包是狭义的，应该是词法作用域闭包。闭包的严格定义只要符合两点就行：能够保存所在词法作用域，并在任意地方任何时刻执行都能访问保存的作用域即可。

**Comment by cumt-robin** [comment]
我这也自行理解了一下，占个楼
https://juejin.im/post/6858052418862235656
